matrix:
  include:
    - os: windows
      language: node_js
      node_js: "10"
    - os: osx
      osx_image: xcode10.2
      language: node_js
      node_js: "10"
    - os: linux
      services: docker
      language: node_js
      node_js: "10"

cache:
  directories:
    - node_modules

script:
  - |
    rm -rf src/dist && yarn && yarn packageAll

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "FILE TO UPLOAD"
  skip_cleanup: true
  on:
    tags: true
  overwrite: true
